### ISSUE TITLE
Package suggestions

### ISSUE THREAD

**Issue by fabiocentofanti** [cran-task-views/FunctionalData#14]
Dear maintainers,

I hope this message finds you well. I would like to suggest the inclusion of the following packages in the "CRAN Task View: Functional Data Analysis":

1. sasfunclust: Sparse and Smooth Functional Clustering (https://cran.r-project.org/web/packages/sasfunclust/index.html)
2. adass: Adaptive Smoothing Spline (AdaSS) Estimator for the Function-on-Function Linear Regression (https://cran.r-project.org/web/packages/adass/index.html)

Thank you for considering these additions.

Best regards,
Fabio Centofanti

**Comment by jdtuck** [comment]
Please provide a pull request to add these.

**Comment by jdtuck** [comment]
Closed by #15
