### ISSUE TITLE
spring cleaning

### ISSUE THREAD

**Issue by fabian-s** [cran-task-views/FunctionalData#2]
I'd like to suggest a renovation of the package list and its structure, i.e.

- weeding out packages that are no longer maintained / poor quality / etc
- adding missing packages 
- restructuring sections into sub-sections where sensible

We are experts in different sub-fields of FDA, so if everybody focuses their attention on their specialties this should be quick and easy. 
Please use the [`spring-cleaning`](https://github.com/cran-task-views/FunctionalData/tree/spring-cleaning) branch for your suggested changes. 
Looking forward to see what we come up with :)

**Comment by fabian-s** [comment]
suggestions for regression: https://github.com/cran-task-views/FunctionalData/commit/81cddfe87a371673f05d708aa46dd817f82fb0db

**Comment by jdtuck** [comment]
I like the change to the regression section. I am thinking about the overall packages currently.

**Comment by julia-wrobel** [comment]
What about adding a visualization  and / or exploratory data section too? I think some of the packages currently in the General section could fall under visualization or FDA

**Comment by fabian-s** [comment]
> What about adding a visualization and / or exploratory data section too?

ooh, yeah. good idea!

> I think some of the packages currently in the General section could fall under visualization or FDA

which ones would you say?

**Comment by julia-wrobel** [comment]
> which ones would you say?

`rainbow`, `refund.shiny` (which I put in the "other" section), `fdaoutlier` (if we make this section Visualization/EDA)

**Comment by jdtuck** [comment]
I like the visualization idea, I would argue form your latest commit that fdasrvf is a general practice as it implements way more than alignment in the SRVF framework

**Comment by fabian-s** [comment]
@julia-wrobel  agreed! If you'd like to make this change I think you can go ahead, both Derek & me support it and nobody objected.

@jdtuck  yeah, I think so too, that's why `fdasrvf` is currently listed in *both* the "General" and the "Registering" sections. I don't think the task view people mind that we list core packages multiple times if they fit into more than one category. I think it makes sense to also keep `fdasrvf` in the "Registering" section because IMO that's where your package really shines and if somebody is looking specifically for registration implementations they should be able to find it under that heading.

**Comment by fabian-s** [comment]
and sorry -- I realize maybe I should have organized this differently so we don't overwrite each other's commits. 

pull requests with specific change sets and discussions about them would have been better than one branch into which everybody commits. 
I'll do better next time.

**Comment by jdtuck** [comment]
started a couple of branches and pull requests for what we identififed.

**Comment by julia-wrobel** [comment]
@jdtucker That's fair, I'm happy to keep fdasrvf it in both the general and alignment sections. I'm thinking of also adding a data section..

**Comment by fabian-s** [comment]
> I'm thinking of also adding a data section..

oh yeah. don't know any other data packages for FD beyond  `fds` but if they exist let's list them

**Comment by jdtuck** [comment]
I don't either, I should just put my data repo into a package at some point....
